mysite/apps/writing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'write/$', views.write.as_view(), name='write'),
	url(r'read/(?P<board>.+)/(?P<id>[0-9]+)/$', views.read.as_view(), name = 'read'),
	url(r'board/(?P<board>.+)/(?P<page>[0-9]+)/$', views.board.as_view(), name='board'),
	url(r'pageControl/$', views.pageControl, name='pageControl'),
	url(r'delete/$', views.delete.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^', include(('page.urls', 'page'), namespace='page')),
    url(r'^writing/', include(('writing.urls', 'writing'), namespace='writing')),
    url(r'^userAccount/', include(('userAccount.urls', 'userAccount'), namespace='userAccount')),
]	+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/apps/writing/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class BoardPost(models.Model):
	title = models.CharField(('Title Of Post'), max_length=100) #글의 제목 입니다.
	content = RichTextField(('Content Of Post')) #글의 내용 입니다.
	tag = models.CharField(max_length=10) #검색할 때 유용하게 쓸 수 있도록 태그를 작성 할 수 있게 합니다.

	#이곳에서부터는 사용자가 접근할 수 없는 메타 정보입니다.
	writedDate = models.DateTimeField(auto_now_add=True) #글이 쓰여진 날짜정보입니다. 따로 자겅할 필요는 없습니다.
	writer = models.CharField(max_length=30) #글의 작성자 id입니다. 따로 작성해야 합니다.#####
	writer_nick_name = models.CharField(max_length=15) # 글 작성자의 nick_name 입니다.
	boardTag = models.CharField(max_length=10) #게시판을 구분하기 위한 boardTag입니다. 사용자는 이 데이터를 직접적으로 수정할 수 없습니다. 따로 작성해야 합니다.####
	alteredDate = models.DateTimeField(auto_now=True) #글이 수정된 날짜입니다. 따로 작성하 필요는 없습니다.
	hits = models.IntegerField(default=0)#글의 조회수 입니다. 추후 추가해야합니다.####

	def __str__(self):
		return self.title

class TestModel(models.Model):
	dateTime = models.DateTimeField()
	dateTime_auto_now = models.DateTimeField(auto_now=True)
	dateTime_auto_now_add = models.DateTimeField(auto_now_add=True)
	helloWorld = models.DateTimeField()

class TestModel22(models.Model):
	dateTime = models.DateTimeField()
	dateTime_auto_now = models.DateTimeField(auto_now=True)
	dateTime_auto_now_add = models.DateTimeField(auto_now_add=True)
	helloWorld = models.DateTimeField()

mysite/apps/writing/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import BoardPost

class BoardForm(forms.ModelForm):
	CHOICES = {
			('free', 'free')
		}
	title = forms.CharField(required=True)
	content = forms.CharField(widget=CKEditorWidget())
	tag = forms.CharField(required=True)
	boardTag = forms.ChoiceField(choices=CHOICES, required=True, label='BoardTag')

	class Meta:
		model = BoardPost
		fields = ('title', 'content', 'tag')

mysite/apps/writing/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View
from .forms import BoardForm
from writing.models import BoardPost
from django.urls import reverse
import math
# Create your views here.

class write(View):
	template_name ='writing/write.html'
	form = 	BoardForm()
	context = {'form': form}
	def get(self, request, *args, **kwargs):
		my_user = request.user.is_authenticated
		if my_user:
			return render(request, self.template_name, self.context)
		else:
			return HttpResponse('로그인 해 주세요.')
		#return HttpResponse(self.template_name)

	def post(self, request, *args, **kwargs):
		title = str(request.POST['title'])
		content = request.POST['content']
		tag  = request.POST['tag']
		boardTag = request.POST['boardTag']
		writer = request.user.username
		writer_nick_name = request.user.nick_name

		userBoardPost = BoardPost.objects.create()
		userBoardPost.title = title
		userBoardPost.content = content
		userBoardPost.tag = tag
		userBoardPost.boardTag = boardTag
		userBoardPost.writer= writer
		userBoardPost.writer_nick_name = writer_nick_name
		userBoardPost.save()
		return HttpResponseRedirect('/writing/board/free/1')
#		output = writer_nick_name
#		return HttpResponse(output)

class read(View):
	template_name = 'writing/read.html'
	context = {}
	def get(self, request, *args, **kwargs):
		userBoardPost = BoardPost.objects.get(boardTag = kwargs['board'], id = kwargs['id'])
		self.context['BoardPost'] = userBoardPost

		try:
			request.session[str(BoardPost.id)]
		except KeyError:
			request.session[str(BoardPost.id)] = True
			userBoardPost.hits += 1
			userBoardPost.save()

		return render(request, self.template_name, self.context)
		#return HttpResponse(userBoardPost.content)

class board(View):
	template_name = 'writing/board.html'
	context = {}

	def get(self, request, *args, **kwargs):
		## 파라미터를 받아와 기본적인 상수를 변수에 저장합니다.
		pageNumber = int(kwargs['page']) # 페이지의 넘버를 저장합니다.
		userBoardPost = BoardPost.objects.all().defer('content').order_by('-id') # 게시판에 있는 모든 게시글을 역순으로 받습니다.
		itemLength = userBoardPost.count() # 게시판에 있는 모든 게시물의 개수를 샙니다.
		pageView = 16

		pageLength = math.ceil( itemLength / pageView ) ## 나타낼 수 있는 총 페이지수를 정합니다.
		pageLengthRemainder = itemLength-pageLength*pageView ## 나타낼 수 있는 총 페에지수 마지막 페이지의 표시할 것들을 나타냅니다. 나머지입니다.
		
		startBoard = (pageNumber-1)*pageView
		endBoard =pageNumber*pageView
		userBoardPost = userBoardPost[startBoard:endBoard] ##페이지에 나타낼 게시글들을 반환합니다. 이걸로 완벽!

		self.context['BoardPost'] = userBoardPost
		self.context['pageNumber'] = pageNumber
		self.context['pageCount'] = pageLength
		self.context['Board'] = kwargs['board']
		return render(request, self.template_name, self.context)

def pageControl(request, *args, **kwargs):
	boardName=request.POST['Board']
	pageNumber=request.POST['pageNumber']
	return HttpResponseRedirect(reverse('writing:board', args=[boardName, pageNumber]))

class delete(View):
	def get(self, request, *args, **kwargs):
		return HttpResponseRedirect('/')

	def post(self, request, *args, **kwargs):
		BoardPostBoardTag = request.POST['BoardPostBoardTag']
		BoardPostId = request.POST['BoardPostId']
		userBoardPost = BoardPost.objects.get(boardTag = BoardPostBoardTag, id = BoardPostId)
		userBoardPost.delete()
		return HttpResponseRedirect('/writing/board/free/1')

mysite/templates/writing/board.html
<!doctype html>
<html>
<head>
{% include 'page/cdn/head.html'%}
</head>

	<body>
		<header><!--네비게이션바-->
			{% include 'page/component/navBar.html' %}
		</header><!--네비게이션바-->



		<div class='container'>
			<div class="page-header">
			<h1>&nbsp&nbsp게시판</h1>
			</div>

			{% include 'writing/component/table.html'%}

		

		<div class='text-center'>
			<form action='{% url 'writing:pageControl' %}' method="POST">
			{% csrf_token %}
			<input type="text" name="pageNumber" size=1 value={{pageNumber}}>
			<label>총 페이지수: {{pageCount}} <input type="hidden" name="Board" value={{Board}}></label>
			</form>
			<a id = "pageNationLeft" href="../{{pageNumber}}-1"><span class="glyphicon glyphicon-menu-left"></span></a>
			<a id = pageNationRight href="#"><span class="glyphicon glyphicon-menu-right" size="100"></span></a>
		</div>
			{% if user.is_active %}
			<div class='text-right'>
			 <a href='{%url 'writing:write' %}' class="btn btn-default" role="button">글 쓰기</a>
			</div>
			{% endif %}

		</div>
	</body>
</html>

{% include 'page/cdn/index_cdn.html'%}

<style>
 a {color: inherit;}
</style>

<script>
var pageNumber = {{pageNumber}};
document.getElementById("pageNationLeft").setAttribute("href", "../"+(pageNumber-1));
document.getElementById("pageNationRight").setAttribute("href", "../"+(pageNumber+1));
</script>

mysite/templates/writing/read.html
<!DOCTYPE HTML>
<html>
<head>
{% include 'page/cdn/head.html'%}
</head>

<body>
		<header><!--네비게이션바-->
			{% include 'page/component/navBar.html' %}
		</header><!--네비게이션바-->
<!--#####################################################################################-->
<!--#####################################################################################-->
<!--#####################################################################################-->
<div class='container' >
		
    <div class="panel panel-default">
		<div class="panel-heading margineBottom">제목: {{BoardPost.title}}</div>

		<div class="panel-body">
			{% autoescape off %}{{BoardPost.content}}{% endautoescape %}
			<div class= 'text-right'>
			{% if BoardPost.writer == user.username %}
			<form method='POST' action='{% url 'writing:delete' %}'>
			{% csrf_token %}
			<input type="submit" class="btn btn-info" value="삭제">
			<input type='hidden' name='BoardPostId' value={{BoardPost.id}}>
			<input type='hidden' name="BoardPostBoardTag" value={{BoardPost.boardTag}}>
			</form>
			{% endif %}
			</div>
		</div>

		<div class="panel-footer">작성자: {{BoardPost.nick_name}}
		<p>조회수: {{BoardPost.hits}}</p>
		</div>
    </div>
	<!-- 여기까지가 게시물.-->

	<div class="form-group">
		<label for="comment">Comment:</label>
		<textarea class="form-control" rows="5" id="comment"></textarea>
		<div class='text-right'>
		코멘트 작성
		</div>
	</div>
</div>
<body>
</html>
{% include 'page/cdn/index_cdn.html'%}

<style>
{% include 'page/common/codingSchool.css' %}
</style>

mysite/templates/writing/write.html
<!DOCTYPE HTML>
<html>
<head>
{% include 'page/cdn/head.html'%}
</head>

<body>
		<header><!--네비게이션바-->
			{% include 'page/component/navBar.html' %}
		</header><!--네비게이션바-->
<!--#####################################################################################-->
<!--#####################################################################################-->
<!--#####################################################################################-->
	<div class='container'>
		<div class='col-md-12'>
			<form name="write" action='{% url 'writing:write' %} ' method="POST">{% csrf_token %}
				{{ form.media }}
				{{ form.as_p }}
			<input type="submit" value="게시글 작성"/>
			</form>
		</div>
	</div>
<body>
</html>

{% include 'page/cdn/index_cdn.html'%}