mysite/apps/page/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main.as_view(), name='main'),
    url(r'^page/notice/$', views.notice.as_view(), name='notice'),
]

mysite/apps/userAccount/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.login.as_view(), name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^sign/$', views.signForm.as_view(), name='sign'),
]

mysite/apps/writing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'write/$', views.write.as_view(), name='write'),
	url(r'read/(?P<board>.+)/(?P<id>[0-9]+)/$', views.read.as_view(), name = 'read'),
	url(r'board/(?P<board>.+)/(?P<page>[0-9]+)/$', views.board.as_view(), name='board'),
	url(r'pageControl/$', views.pageControl, name='pageControl'),
	url(r'delete/$', views.delete.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^', include(('page.urls', 'page'), namespace='page')),
    url(r'^writing/', include(('writing.urls', 'writing'), namespace='writing')),
    url(r'^userAccount/', include(('userAccount.urls', 'userAccount'), namespace='userAccount')),
]	+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/templates/page/component/navBar.html
 <!-- NAVER BRAND BAR
===========================================-->
        <div class="navbar-wrapper">
            <nav class="navbar navbar-default navbar-static-top">
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" style="border-color:white;color:white">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="/" style="">Coding School</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                    <li><a href='{% url 'page:notice' %}'>알림</a></li><!--active클래스를 넣어주세요!-->
                    <li><a href='{% url 'writing:board' 'free' '1' %}'>게시판</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">언어<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-header">문법</li>
						<li><a href="#">JavaScript</a></li>
                        <li><a href="#">C++</a></li>
                        <li><a href="#">Python</a></li>
                        <li role="separator" class="divider"></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">알고리즘<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-header">알고리즘</li>
                        <li><a href="#">자료구조</a></li>
                        <li><a href="#">시스템 알고리즘</a></li>
                        <li><a href="#">데이터 알고리즘</a></li>
                        <li role="separator" class="divider"></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">활용<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-header">웹</li>
                        <li><a href="#">Django</a></li>
                        <li><a href="#">데이터 시각화</a></li>
                        <li role="separator" class="divider"></li>
                      </ul>
                    </li>
                  </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_active %}
                        <li><a href='{% url 'userAccount:login' %}' ><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        <li><a href='{% url 'userAccount:sign' %}'><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        {% else %}
                        <li><a href='{% url 'userAccount:logout' %}'><span class="glyphicon glyphicon-log-out"></span> LogOut</a></li>
                        {% endif %}
                    </ul>

                </div>
              </div>
            </nav>
        </div>
               <!-- NAVER BRAND BAR
===========================================-->